export const BOOKS_LOADED = "ITEM/BOOKS_LOADED";
export const BOOKS_REQUESTED = "ITEM/BOOKS_REQUESTED";
export const BOOKS_ERROR = "ITEM/BOOKS_ERROR";
export const BOOK_ADDED_TO_CART = "ITEM/BOOK_ADDED_TO_CART";
export const BOOK_REMOVE_FROM_CART = "ITEM/BOOK_REMOVE_FROM_CART";
export const ALL_BOOKS_REMOVE_FROM_CART = "ITEM/ALL_BOOK_REMOVE_FROM_CART";

